server:
  port: 8191

spring:
  application:
    name:


        - id: cart-service
          uri: http://localhost:8191/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
#            - PrefixPath=/market-cart
            - PrefixPath=/web-market-cart
            - JwtAuthFilter

        - id: auth-service
          uri: http://localhost:8188/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-auth
            - JwtAuthFilter

